import { Toaster } from "sonner"
import type { Metadata } from "next"
import { Outfit } from "next/font/google"

import { cn } from "@/lib/utils"
import { Providers } from "@/components/providers"

import "./globals.css"

const font = Outfit({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Site Chatter",
  description: "Generated by create next app"
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className="dark">
      <body className={cn(font.className, "min-h-screen antialiased")}>
        <Providers>{children}</Providers>
        <Toaster theme="dark" richColors position="bottom-center" />
      </body>
    </html>
  )
}

export default RootLayout
